asv_hparams:
  hparams:
    ecapa_tdnn:
      C: 1024
      attn_dims: 256
      bottle_neck:
        dilation:
        - 2
        - 3
        - 4
        kernel_size: 3
        scale: 8
      embedding_size: 192
      fixed_C: 1536
      kernel_size: 5
    loss:
      margin: 0.2
      scale: 30
    loss_func: aam_softmax
    optim:
      lr: 0.01
      lr_decay: 0.98
      wd: 2.0e-05
    preprocessing:
      mel:
        channels: 80
        fmax: 7600
        fmin: 20
        log_base: null
      num_frames: 200
      signal:
        max_wav_value: 32768.0
        sampling_rate: 16000
        segment_length: 32768
      stft:
        filter_length: 512
        hop_length: 160
        win_length: 400
        window: hann
    sinc_net:
      cnn_N_filt:
      - 80
      - 60
      - 60
      cnn_act:
      - leaky_relu
      - leaky_relu
      - leaky_relu
      cnn_drop:
      - 0.0
      - 0.0
      - 0.0
      cnn_len_filt:
      - 251
      - 5
      - 5
      cnn_max_pool_len:
      - 3
      - 3
      - 3
      cnn_use_batchnorm:
      - false
      - false
      - false
      cnn_use_batchnorm_inp: false
      cnn_use_laynorm:
      - true
      - true
      - true
      cnn_use_laynorm_inp: true
      is_flat: false
  model:
    backend: ecapa_tdnn
    frontend: sinc_net
cm_hparams:
  hparams:
    assist:
      filts:
      - 70
      - - 1
        - 32
      - - 32
        - 32
      - - 32
        - 64
      - - 64
        - 64
      first_conv: 128
      gat_dims:
      - 64
      - 32
      pool_ratios:
      - 0.5
      - 0.7
      - 0.5
      - 0.5
      temperatures:
      - 2.0
      - 2.0
      - 100.0
      - 100.0
    loss:
      margin: 0.2
      scale: 30
    loss_func: aam_softmax
    optim:
      lr: 0.01
      lr_decay: 0.98
      wd: 2.0e-05
    preprocessing:
      mel:
        channels: 80
        fmax: 7600
        fmin: 20
        log_base: null
      num_frames: 200
      signal:
        max_wav_value: 32768.0
        sampling_rate: 16000
        segment_length: 32768
      stft:
        filter_length: 512
        hop_length: 160
        win_length: 400
        window: hann
  model:
    backend: assist
    frontend: none
